# Generated by Django 2.2.8 on 2019-12-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_auto_20191205_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('SellingPrice', models.IntegerField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
