# Generated by Django 2.2.8 on 2019-12-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
