# Generated by Django 2.2.8 on 2019-12-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_auto_20191208_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='Price',
        ),
    ]
