# Generated by Django 2.2.8 on 2019-12-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0006_remove_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
